### ISSUE TITLE
How do you test HE after fine-tuned on CodeLLama？

### ISSUE THREAD

**Issue by swtheing** [ise-uiuc/magicoder#10]
We use 110k data to fine-tune CodeLLama and test the HE and the pass@1 is 60.6%. I wonder some settings are not same between our experiments.

**Comment by UniverseFly** [comment]
Hi, we finetuned CodeLlama-Python-7B with 75K OSS-Instruct first for 2 epochs and then 110K evol-instruct data for another 2 epochs. And the HumanEval prompt we used is give in The hyperparameter setting is given in the paper and the prompt we used is showed at [experiments/text2code.py](https://github.com/ise-uiuc/magicoder/blob/830ef3bae6c964d913937e4146817d5ecf1ab106/experiments/text2code.py).

Hope this can help with your case and we will later document how to reproduce the experimental results in the paper.
