### ISSUE TITLE
Wrong MBPP pass@1 of CodeLlama-Python

### ISSUE THREAD

**Issue by Keytoyze** [ise-uiuc/magicoder#11]
Hello,

I observed that in your paper, the MBPP pass@1 for CodeLlama-Python is listed as 57.6% (see Table 1). But, according to the original CodeLlama paper ([1; Table 2]), it's actually 47.6%. Could you please update this?

Reference:
[1] https://arxiv.org/pdf/2308.12950.pdf

**Comment by UniverseFly** [comment]
Hi, thanks for asking. We follow the [evalplus leaderboard](https://evalplus.github.io/leaderboard.html) results which share a consistent setting among all models, so they are not exactly the same from the original paper but are reproducible.
