### ISSUE TITLE
Evaluation codes not found

### ISSUE THREAD

**Issue by BinSean** [ise-uiuc/magicoder#13]
Hello, 

Thanks for providing such an amazing repo for LLMs to generate codes.
I am impressive that magicoder got a great result in HumanEval however I can't find the evaluation code for this.
It's great if the evaluation code is made available.

**Comment by UniverseFly** [comment]
Hi, the evaluation code is all under `/experiments`. We will document the procedure to reproduce the numbers later.

**Comment by BinSean** [comment]
Thank you very much for the hint!

I have been studying codes in /experiments these days. 
I spotted the code description of __init__.py in /experiments, '[feat: training and humaneval evaluation code]'. I thought I finally found the codes for HumanEval, but nothing inside. 
I tried to follow the instructions in README.md , I can't figure out what and where the 'data-clean-decontaminated.jsonl' is.

It will be great if providing more detailed descriptions.

**Comment by UniverseFly** [comment]
Here is the code for HumanEval and MBPP evaluation: https://github.com/ise-uiuc/magicoder/blob/main/experiments/text2code.py

It will write results into a jsonl file that has [evalplus](https://github.com/evalplus/evalplus)-compatible format. You can then refer to evalplus documentation to get the pass@1 results.
