### ISSUE TITLE
can you consider adding my explanation on how to use magicoder in text-generation-webui 

### ISSUE THREAD

**Issue by Sairampv98** [ise-uiuc/magicoder#15]
After experimenting with text-generation-webui by oobabooga I found the following things 
-Magicoder models are all instruct only models (no chat/chat-instruct)
-you need to create a new custom template under **parameters/instruction template** tab 
-you also need to change these values under **parameters/generation**  tab (max-new-tokens=1024,top_p=0.9,top_k=50,repetition-penality=1,repetetion-penality-range=1024) 
-copy the content in the text file to custom template/instruction template 
[instruction-template-magicode.txt](https://github.com/ise-uiuc/magicoder/files/13696372/instruction-template-magicode.txt)

_**I took the generation parameters from deepseek-coder/demo/app.py**
**The instruction template is edited from airoborous-v1.2 after comparing it with its prompt template**_

**Comment by ruizcrp** [comment]
Which model-loader did you use?
