### ISSUE TITLE
small models

### ISSUE THREAD

**Issue by BecomeAllan** [ise-uiuc/magicoder#21]
thanks for the awesome work!!! My question is, why not deepseek-coder 1b ???? :((

this enables amazing apps on edge devices, like in small robots decision makers. would be a great model if using chain of code and Programmatic Reasoning.

https://arxiv.org/abs/2312.03052
https://sites.google.com/view/chain-of-code

**Comment by UniverseFly** [comment]
Thanks for the suggestion! We'll definitely look into smaller models.
