### ISSUE TITLE
The model outputs nothing but "\n"  HELP! 😭

### ISSUE THREAD

**Issue by mmmrvector** [ise-uiuc/magicoder#22]
![WX20231226-203314@2x](https://github.com/ise-uiuc/magicoder/assets/28217377/80eda68f-d5d7-43cf-8745-7a145b39bbf2)
I followed the demo instruction in github and ran the model in jupyter, but just got nothing but "\n". 
Can anyone tell me what's wrong?

**Comment by mmmrvector** [comment]
![WX20231226-203721@2x](https://github.com/ise-uiuc/magicoder/assets/28217377/9857492c-638d-47b1-9e77-fd9542473fb2)
Here is the code

**Comment by FoxxComz** [comment]
I got same problem. Have u solved it?

**Comment by mmmrvector** [comment]
> I got same problem. Have u solved it?

I updated some python packages to the latest version and restart the jupyter kernel. 
After that, I didn't use this model any more....

**Comment by FoxxComz** [comment]
thanks bro, i think i need to open another issue
