### ISSUE TITLE
Data collection and generation

### ISSUE THREAD

**Issue by monaj07** [ise-uiuc/magicoder#29]
Thanks for releasing your research codes to everyone.
The [variables here](https://github.com/ise-uiuc/magicoder/blob/main/experiments/collect_seed_documents.py#L35) I found a bit difficult to figure out what they are for.
Can you please explain them?
And in general, could you please add a more comprehensive readme about the data collection/generation parts of the code base?
Thanks!

**Comment by UniverseFly** [comment]
Hi, you can find the instructions at [README-DEV.md](https://github.com/ise-uiuc/magicoder/blob/c900e74a577ea06d3a397b34745d0c920a91f1f7/README-DEV.md). Internally it will load `starcoderdata` and collect the seeds in tandem with the data generation.
