### ISSUE TITLE
Any plans for a 33b fine tune? 

### ISSUE THREAD

**Issue by alexconstant9108** [ise-uiuc/magicoder#6]
Awesome models! Great job guys! :)
I am wondering if you plan to also finetune on top of deepseek-coder-33b-instruct as well? I wonder how high the evaluations will go with that model :)

**Comment by UniverseFly** [comment]
Thanks!! Yes, finetuning larger models is in our plan, and we will get people informed when we have the results!

**Comment by alexconstant9108** [comment]
@UniverseFly That's fantastic. Thank you! Looking forward to your new releases! :)
