### ISSUE TITLE
Optimizer selection

### ISSUE THREAD

**Issue by VoiceBeer** [ise-uiuc/magicoder#7]
Hi, thx for the brilliant work!

I am curious about the decision to use Adafactor as the optimizer for Magicoder. Have other options been explored or tried in this context? 🤔

**Comment by UniverseFly** [comment]
It's mainly because adafactor saves the gpu memory:) We can then do vanilla DDP without applying ZeRO, which enables faster training. We definitely encourage people to try other optimizers!

**Comment by VoiceBeer** [comment]
Oh ic, make sense, again great work, thx for the inspiration and the datasets!
